extern NSString * const DESCRIPTOR_RESPONSE_UUID;
extern NSString * const DESCRIPTOR_RESPONSE_ID;
extern NSString * const DESCRIPTOR_RESPONSE_VALUE;
extern NSString * const DESCRIPTOR_RESPONSE_CHARACTERISTIC_UUID;
extern NSString * const DESCRIPTOR_RESPONSE_CHARACTERISTIC_ID;
extern NSString * const DESCRIPTOR_RESPONSE_SERVICE_UUID;
extern NSString * const DESCRIPTOR_RESPONSE_SERVICE_ID;
