// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bledata.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Bledata.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - BleDataBledataRoot

@implementation BleDataBledataRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - BleDataBledataRoot_FileDescriptor

static GPBFileDescriptor *BleDataBledataRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                 objcPrefix:@"BleData"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum BleDataLogLevelMessage

GPBEnumDescriptor *BleDataLogLevelMessage_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Verbose\000Debug\000Info\000Warning\000Error\000None\000";
    static const int32_t values[] = {
        BleDataLogLevelMessage_Verbose,
        BleDataLogLevelMessage_Debug,
        BleDataLogLevelMessage_Info,
        BleDataLogLevelMessage_Warning,
        BleDataLogLevelMessage_Error,
        BleDataLogLevelMessage_None,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(BleDataLogLevelMessage)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:BleDataLogLevelMessage_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL BleDataLogLevelMessage_IsValidValue(int32_t value__) {
  switch (value__) {
    case BleDataLogLevelMessage_Verbose:
    case BleDataLogLevelMessage_Debug:
    case BleDataLogLevelMessage_Info:
    case BleDataLogLevelMessage_Warning:
    case BleDataLogLevelMessage_Error:
    case BleDataLogLevelMessage_None:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum BleDataBluetoothStateMessage

GPBEnumDescriptor *BleDataBluetoothStateMessage_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Resetting\000Unsupported\000Unauthoriz"
        "ed\000PoweredOff\000PoweredOn\000";
    static const int32_t values[] = {
        BleDataBluetoothStateMessage_Unknown,
        BleDataBluetoothStateMessage_Resetting,
        BleDataBluetoothStateMessage_Unsupported,
        BleDataBluetoothStateMessage_Unauthorized,
        BleDataBluetoothStateMessage_PoweredOff,
        BleDataBluetoothStateMessage_PoweredOn,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(BleDataBluetoothStateMessage)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:BleDataBluetoothStateMessage_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL BleDataBluetoothStateMessage_IsValidValue(int32_t value__) {
  switch (value__) {
    case BleDataBluetoothStateMessage_Unknown:
    case BleDataBluetoothStateMessage_Resetting:
    case BleDataBluetoothStateMessage_Unsupported:
    case BleDataBluetoothStateMessage_Unauthorized:
    case BleDataBluetoothStateMessage_PoweredOff:
    case BleDataBluetoothStateMessage_PoweredOn:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - BleDataScanSettingsMessage

@implementation BleDataScanSettingsMessage

@dynamic scanMode;
@dynamic callbackType;

typedef struct BleDataScanSettingsMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t scanMode;
  int32_t callbackType;
} BleDataScanSettingsMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "scanMode",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanSettingsMessage_FieldNumber_ScanMode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BleDataScanSettingsMessage__storage_, scanMode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "callbackType",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanSettingsMessage_FieldNumber_CallbackType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BleDataScanSettingsMessage__storage_, callbackType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BleDataScanSettingsMessage class]
                                     rootClass:[BleDataBledataRoot class]
                                          file:BleDataBledataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BleDataScanSettingsMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\010\000\002\014\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BleDataScanFilterMessage

@implementation BleDataScanFilterMessage

@dynamic deviceName;
@dynamic deviceAddress;
@dynamic serviceUuid;
@dynamic serviceUuidMask;
@dynamic serviceDataUuid;
@dynamic serviceData;
@dynamic serviceDataMask;
@dynamic manufacturerId;
@dynamic manufacturerData;
@dynamic manufacturerDataMask;

typedef struct BleDataScanFilterMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t manufacturerId;
  NSString *deviceName;
  NSString *deviceAddress;
  NSString *serviceUuid;
  NSString *serviceUuidMask;
  NSString *serviceDataUuid;
  NSData *serviceData;
  NSData *serviceDataMask;
  NSData *manufacturerData;
  NSData *manufacturerDataMask;
} BleDataScanFilterMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "deviceName",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_DeviceName,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, deviceName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceAddress",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_DeviceAddress,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, deviceAddress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "serviceUuid",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_ServiceUuid,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, serviceUuid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "serviceUuidMask",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_ServiceUuidMask,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, serviceUuidMask),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "serviceDataUuid",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_ServiceDataUuid,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, serviceDataUuid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "serviceData",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_ServiceData,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, serviceData),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "serviceDataMask",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_ServiceDataMask,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, serviceDataMask),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "manufacturerId",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_ManufacturerId,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, manufacturerId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "manufacturerData",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_ManufacturerData,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, manufacturerData),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "manufacturerDataMask",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanFilterMessage_FieldNumber_ManufacturerDataMask,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(BleDataScanFilterMessage__storage_, manufacturerDataMask),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BleDataScanFilterMessage class]
                                     rootClass:[BleDataBledataRoot class]
                                          file:BleDataBledataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BleDataScanFilterMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\n\001\n\000\002\r\000\003\013\000\004\017\000\005\017\000\006\013\000\007\017\000\010\016\000\t\020\000\n\024\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BleDataBleDeviceMessage

@implementation BleDataBleDeviceMessage

@dynamic macAddress;
@dynamic name;
@dynamic rssi;
@dynamic mtu;

typedef struct BleDataBleDeviceMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t rssi;
  int32_t mtu;
  NSString *macAddress;
  NSString *name;
} BleDataBleDeviceMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "macAddress",
        .dataTypeSpecific.className = NULL,
        .number = BleDataBleDeviceMessage_FieldNumber_MacAddress,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BleDataBleDeviceMessage__storage_, macAddress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = BleDataBleDeviceMessage_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BleDataBleDeviceMessage__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "rssi",
        .dataTypeSpecific.className = NULL,
        .number = BleDataBleDeviceMessage_FieldNumber_Rssi,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BleDataBleDeviceMessage__storage_, rssi),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "mtu",
        .dataTypeSpecific.className = NULL,
        .number = BleDataBleDeviceMessage_FieldNumber_Mtu,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BleDataBleDeviceMessage__storage_, mtu),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BleDataBleDeviceMessage class]
                                     rootClass:[BleDataBledataRoot class]
                                          file:BleDataBledataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BleDataBleDeviceMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BleDataScanResultMessage

@implementation BleDataScanResultMessage

@dynamic hasBleDeviceMessage, bleDeviceMessage;
@dynamic rssi;
@dynamic timestampNanos;
@dynamic scanCallbackTypeMessage;

typedef struct BleDataScanResultMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t rssi;
  int32_t scanCallbackTypeMessage;
  BleDataBleDeviceMessage *bleDeviceMessage;
  uint64_t timestampNanos;
} BleDataScanResultMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "bleDeviceMessage",
        .dataTypeSpecific.className = GPBStringifySymbol(BleDataBleDeviceMessage),
        .number = BleDataScanResultMessage_FieldNumber_BleDeviceMessage,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BleDataScanResultMessage__storage_, bleDeviceMessage),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "rssi",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanResultMessage_FieldNumber_Rssi,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BleDataScanResultMessage__storage_, rssi),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "timestampNanos",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanResultMessage_FieldNumber_TimestampNanos,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BleDataScanResultMessage__storage_, timestampNanos),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "scanCallbackTypeMessage",
        .dataTypeSpecific.className = NULL,
        .number = BleDataScanResultMessage_FieldNumber_ScanCallbackTypeMessage,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BleDataScanResultMessage__storage_, scanCallbackTypeMessage),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BleDataScanResultMessage class]
                                     rootClass:[BleDataBledataRoot class]
                                          file:BleDataBledataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BleDataScanResultMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\020\000\003\016\000\004\027\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BleDataConnectToDeviceDataMessage

@implementation BleDataConnectToDeviceDataMessage

@dynamic macAddress;
@dynamic isAutoConnect;
@dynamic requestMtu;

typedef struct BleDataConnectToDeviceDataMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t requestMtu;
  NSString *macAddress;
} BleDataConnectToDeviceDataMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "macAddress",
        .dataTypeSpecific.className = NULL,
        .number = BleDataConnectToDeviceDataMessage_FieldNumber_MacAddress,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BleDataConnectToDeviceDataMessage__storage_, macAddress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isAutoConnect",
        .dataTypeSpecific.className = NULL,
        .number = BleDataConnectToDeviceDataMessage_FieldNumber_IsAutoConnect,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "requestMtu",
        .dataTypeSpecific.className = NULL,
        .number = BleDataConnectToDeviceDataMessage_FieldNumber_RequestMtu,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BleDataConnectToDeviceDataMessage__storage_, requestMtu),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BleDataConnectToDeviceDataMessage class]
                                     rootClass:[BleDataBledataRoot class]
                                          file:BleDataBledataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BleDataConnectToDeviceDataMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\n\000\002\r\000\003\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BleDataSimpleTransactionMessage

@implementation BleDataSimpleTransactionMessage

@dynamic transactionId;

typedef struct BleDataSimpleTransactionMessage__storage_ {
  uint32_t _has_storage_[1];
  NSString *transactionId;
} BleDataSimpleTransactionMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "transactionId",
        .dataTypeSpecific.className = NULL,
        .number = BleDataSimpleTransactionMessage_FieldNumber_TransactionId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BleDataSimpleTransactionMessage__storage_, transactionId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BleDataSimpleTransactionMessage class]
                                     rootClass:[BleDataBledataRoot class]
                                          file:BleDataBledataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BleDataSimpleTransactionMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BleDataRequestMtuTransactionMessage

@implementation BleDataRequestMtuTransactionMessage

@dynamic transactionId;
@dynamic macAddress;
@dynamic mtu;

typedef struct BleDataRequestMtuTransactionMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t mtu;
  NSString *transactionId;
  NSString *macAddress;
} BleDataRequestMtuTransactionMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "transactionId",
        .dataTypeSpecific.className = NULL,
        .number = BleDataRequestMtuTransactionMessage_FieldNumber_TransactionId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BleDataRequestMtuTransactionMessage__storage_, transactionId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "macAddress",
        .dataTypeSpecific.className = NULL,
        .number = BleDataRequestMtuTransactionMessage_FieldNumber_MacAddress,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BleDataRequestMtuTransactionMessage__storage_, macAddress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "mtu",
        .dataTypeSpecific.className = NULL,
        .number = BleDataRequestMtuTransactionMessage_FieldNumber_Mtu,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BleDataRequestMtuTransactionMessage__storage_, mtu),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BleDataRequestMtuTransactionMessage class]
                                     rootClass:[BleDataBledataRoot class]
                                          file:BleDataBledataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BleDataRequestMtuTransactionMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\r\000\002\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BleDataReadRSSIForDeviceMessage

@implementation BleDataReadRSSIForDeviceMessage

@dynamic transactionId;
@dynamic macAddress;

typedef struct BleDataReadRSSIForDeviceMessage__storage_ {
  uint32_t _has_storage_[1];
  NSString *transactionId;
  NSString *macAddress;
} BleDataReadRSSIForDeviceMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "transactionId",
        .dataTypeSpecific.className = NULL,
        .number = BleDataReadRSSIForDeviceMessage_FieldNumber_TransactionId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BleDataReadRSSIForDeviceMessage__storage_, transactionId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "macAddress",
        .dataTypeSpecific.className = NULL,
        .number = BleDataReadRSSIForDeviceMessage_FieldNumber_MacAddress,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BleDataReadRSSIForDeviceMessage__storage_, macAddress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BleDataReadRSSIForDeviceMessage class]
                                     rootClass:[BleDataBledataRoot class]
                                          file:BleDataBledataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BleDataReadRSSIForDeviceMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\r\000\002\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
