part of flutter_ble_lib;

const _createClient = "createClient";
const _destroyClient = "destroyClient";
const _cancelTransaction = "cancelTransaction";
const _setLogLevel = "setLogLevel";
const _logLevel = "logLevel";
const _state = "state";
const _startDeviceScan = "startDeviceScan";
const _stopDeviceScan = "stopDeviceScan";
const _requestMTUForDevice = "requestMTUForDevice";
const _readRSSIForDevice = "readRSSIForDevice";
const _connectToDevice = "connectToDevice";
const _cancelDeviceConnection = "cancelDeviceConnection";
const _isDeviceConnected = "isDeviceConnected";
const _discoverAllServicesAndCharacteristicsForDevice = "discoverAllServicesAndCharacteristicsForDevice";
const _servicesForDevice = "servicesForDevice";
const _characteristicsForDevice = "characteristicsForDevice";
const _characteristicsForService = "characteristicsForService";
const _writeCharacteristicForDevice = "writeCharacteristicForDevice";
const _writeCharacteristic = "writeCharacteristic";
const _readCharacteristicForDevice = "readCharacteristicForDevice";
const _readCharacteristicForService = "readCharacteristicForService";
const _readCharacteristic = "readCharacteristic";
const _monitorCharacteristicForDevice = "monitorCharacteristicForDevice";
const _monitorCharacteristicForService = "monitorCharacteristicForService";
const _monitorCharacteristic = "monitorCharacteristic";