extern NSString * const DART_METHOD_NAME_CREATE_CLIENT;

extern NSString * const DART_METHOD_NAME_START_DEVICE_SCAN;
extern NSString * const DART_METHOD_NAME_STOP_DEVICE_SCAN;

extern NSString * const DART_METHOD_NAME_CONNECT_TO_DEVICE;
extern NSString * const DART_METHOD_NAME_DISCONNECT_OR_CANCEL_CONNECTION;
extern NSString * const DART_METHOD_NAME_IS_DEVICE_CONNECTED;

extern NSString * const DART_METHOD_NAME_DISCOVER_ALL_SERVICES_AND_CHARACTERISTICS;

extern NSString * const DART_METHOD_NAME_READ_CHARACTERISTIC_FOR_DEVICE;
extern NSString * const DART_METHOD_NAME_READ_CHARACTERISTIC_FOR_SERVICE;
extern NSString * const DART_METHOD_NAME_READ_CHARACTERISTIC_FOR_IDENTIFIER;

extern NSString * const DART_METHOD_NAME_WRITE_CHARACTERISTIC_FOR_DEVICE;
extern NSString * const DART_METHOD_NAME_WRITE_CHARACTERISTIC_FOR_SERVICE;
extern NSString * const DART_METHOD_NAME_WRITE_CHARACTERISTIC_FOR_IDENTIFIER;
