extern NSString * const DART_RESULT_CHARACTERISTICS;
extern NSString * const DART_RESULT_SERVICE_ID;
extern NSString * const DART_RESULT_SERVICE_UUID;

extern NSString * const DART_RESULT_CHARACTERISTIC_ID;
extern NSString * const DART_RESULT_CHARACTERISTIC_UUID;
extern NSString * const DART_RESULT_DEVICE_IDENTIFIER;
extern NSString * const DART_RESULT_IS_INDICATABLE;
extern NSString * const DART_RESULT_IS_NOTIFIABLE;
extern NSString * const DART_RESULT_IS_NOTIFYING;
extern NSString * const DART_RESULT_IS_READABLE;
extern NSString * const DART_RESULT_IS_WRITABLE_WITH_RESPONSE;
extern NSString * const DART_RESULT_IS_WRITABLE_WITHOUT_RESPONSE;
extern NSString * const DART_RESULT_VALUE;
