extern NSString * const DART_CALL_ARGUMENT_DEVICE_ID;

extern NSString * const DART_CALL_ARGUMENT_PERIPHERAL_ID;
extern NSString * const DART_CALL_ARGUMENT_IS_CONNECTABLE;
extern NSString * const DART_CALL_ARGUMENT_LOCAL_NAME;
extern NSString * const DART_CALL_ARGUMENT_MANUFACTURER_DATA;
extern NSString * const DART_CALL_ARGUMENT_MTU;
extern NSString * const DART_CALL_ARGUMENT_NAME;
extern NSString * const DART_CALL_ARGUMENT_OVERFLOW_UUIDS;
extern NSString * const DART_CALL_ARGUMENT_RSSI;
extern NSString * const DART_CALL_ARGUMENT_SERVICE_DATA;
extern NSString * const DART_CALL_ARGUMENT_SERVICE_UUIDS;
extern NSString * const DART_CALL_ARGUMENT_SOLICITED_SERVICE_UUIDS;
extern NSString * const DART_CALL_ARGUMENT_TX_POWER_LEVEL;

extern NSString * const DART_CALL_CONNECTION_STATE;

extern NSString * const DART_CALL_ARGUMENT_CHARACTERISTIC_IDENTIFIER;
