extern NSString * const DART_METHOD_NAME_CREATE_CLIENT;

extern NSString * const DART_METHOD_NAME_START_DEVICE_SCAN;
extern NSString * const DART_METHOD_NAME_STOP_DEVICE_SCAN;

extern NSString * const DART_METHOD_NAME_CONNECT_TO_DEVICE;
extern NSString * const DART_METHOD_NAME_IS_DEVICE_CONNECTED;
