extern NSString * const PLATFORM_METHOD_NAME_SIMULATE;

extern NSString * const PLATFORM_METHOD_NAME_PUBLISH_SCAN_RESULT;
extern NSString * const PLATFORM_METHOD_NAME_PUBLISH_CONNECTION_STATE;
extern NSString * const PLATFORM_METHOD_NAME_PUBLISH_CHARACTERISTIC_UPADTE;
extern NSString * const PLATFORM_METHOD_NAME_PUBLISH_CHARACTERISTIC_MONITORING_ERROR;
