extern NSString * const SIMULATION_ARGUMENT_NAME_DEVICE_ID;

extern NSString * const SIMULATION_ARGUMENT_NAME_SERVICE_ID;
extern NSString * const SIMULATION_ARGUMENT_NAME_CHARACTERISTICS;
extern NSString * const SIMULATION_ARGUMENT_NAME_SERVICE_UUID;
