extern NSString * const ARGUMENT_KEY_RESTORE_STATE_IDENTIFIER;
extern NSString * const ARGUMENT_KEY_SCAN_MODE;
extern NSString * const ARGUMENT_KEY_ALLOW_DUPLICATES;
extern NSString * const ARGUMENT_KEY_CALLBACK_TYPE;
extern NSString * const ARGUMENT_KEY_UUIDS;

extern NSString * const ARGUMENT_KEY_TRANSACTION_ID;

extern NSString * const ARGUMENT_KEY_DEVICE_IDENTIFIER;
extern NSString * const ARGUMENT_KEY_IS_AUTO_CONNECT;
extern NSString * const ARGUMENT_KEY_REQUEST_MTU;
extern NSString * const ARGUMENT_KEY_REFRESH_GATT;
extern NSString * const ARGUMENT_KEY_TIMEOUT_MILLIS;
extern NSString * const ARGUMENT_KEY_EMIT_CURRENT_VALUE;

extern NSString * const ARGUMENT_KEY_LOG_LEVEL;

extern NSString * const ARGUMENT_KEY_SERVICE_UUID;
extern NSString * const ARGUMENT_KEY_SERVICE_ID;
extern NSString * const ARGUMENT_KEY_CHARACTERISTIC_UUID;
extern NSString * const ARGUMENT_KEY_CHARACTERISTIC_IDENTIFIER;
extern NSString * const ARGUMENT_KEY_VALUE;
extern NSString * const ARGUMENT_KEY_WITH_RESPONSE;

extern NSString * const ARGUMENT_KEY_DESCRIPTOR_UUID;
extern NSString * const ARGUMENT_KEY_DESCRIPTOR_IDENTIFIER;

extern NSString * const ARGUMENT_KEY_MTU;

extern NSString * const ARGUMENT_KEY_DEVICE_IDENTIFIERS;
