extern NSString * const CHANNEL_NAME_FLUTTER_BLE_LIB;
extern NSString * const CHANNEL_NAME_ADAPTER_STATE_CHANGES;
extern NSString * const CHANNEL_NAME_STATE_RESTORE_EVENTS;
extern NSString * const CHANNEL_NAME_SCANNING_EVENTS;
extern NSString * const CHANNEL_NAME_CONNECTION_STATE_CHANGE_EVENTS;
extern NSString * const CHANNEL_NAME_MONITOR_CHARACTERISTIC;
